### ISSUE TITLE
Random crash on load

### ISSUE THREAD

**Issue by SamsamTS** [Simie/PrecisionEngineering#1]
There seems to be a crash happening that might be caused by your mod :

========== OUTPUTING STACK TRACE ==================

000000013FF641E6 (Cities) Scripting::ScriptingWrapperFor
0000000004E0E68C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
0000000004E0E5AD (Mono JIT Code) UnityEngine.Object:FindObjectOfType (System.Type)
00000000564BFBA9 (Mono JIT Code) UnityEngine.Object:FindObjectOfType<object> ()
0000000056578E43 (Mono JIT Code) PrecisionEngineering.PrecisionEngineeringManager:get_NetToolProxy ()
0000000056578D1A (Mono JIT Code) PrecisionEngineering.PrecisionEngineeringManager:Load ()
0000000056578A89 (Mono JIT Code) PrecisionEngineering.PrecisionEngineeringManager:SimulationStepImpl (int)
00000000845D47BD (Mono JIT Code) SimulationManagerBase`2<object, object>:SimulationStep (int)
0000000056578A25 (Mono JIT Code) PrecisionEngineering.PrecisionEngineeringManager:ISimulationManager.SimulationStep (int)
0000000030551FC4 (Mono JIT Code) SimulationManager:SimulationStep ()
0000000004E908DB (Mono JIT Code) SimulationManager:SimulationThread ()
0000000004DD8BBB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
000007FEE9284063 (mono) mono_set_defaults
000007FEE91D8399 (mono) mono_runtime_invoke
000007FEE9201767 (mono) mono_thread_interruption_request_flag
000007FEE92B68A9 (mono) unity_mono_method_is_generic
00000000771159CD (kernel32) BaseThreadInitThunk
000000007724B891 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

It's not a major issue as it doesn't happen all the time but I thought you might want to check it out.

**Comment by Simie** [comment]
Thanks for reporting this, I have an idea about why this might be happening.

**Comment by Simie** [comment]
Should be fixed in 8a430db (not released on the workshop yet)
