### ISSUE TITLE
Compass Feature Request

### ISSUE THREAD

**Issue by NixillUmbreon** [Simie/PrecisionEngineering#2]
Displays the heading of the road relative to north (from start to end points). Toggle which angle snap is used with a button on the toolbar (default protractor) and then use CTRL.

**Comment by Simie** [comment]
I'm planning to add compass-snapping when placing a road on a blank space (where there is currently no snapping, as there is no point of reference). Is there a reason you'd need it at other times?

**Comment by NixillUmbreon** [comment]
Not that I can think of right now, but I'm sure someone could think of
something eventually.

On 24 May 2015 at 09:43, Simon Moles <notifications@github.com> wrote:

> I'm planning to add compass-snapping when placing a road on a blank space
> (where there is currently no snapping, as there is no point of reference).
> Is there a reason you'd need it at other times?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simie/PrecisionEngineering/issues/2#issuecomment-105017871>
> .
>



-- 
Sincerely,

Steven Hammontree
