### ISSUE TITLE
Infinite Grid feature request

### ISSUE THREAD

**Issue by NixillUmbreon** [Simie/PrecisionEngineering#3]
Infinite Grid: The normal grid of cells, but centered on the middle of the map and aligned with the map. Toggleable by a button on the toolbar. Reset with a button on the toolbar. Hold ALT and click within another grid to realign the infinite grid to the other one. Hold ALT and click and drag to realign the grid manually, and ALT-right-click-drag to rotate it.

**Comment by Simie** [comment]
A bit beyond the scope for the mod for now. I'm going to close this.
